CREATE TABLE `t_user` (
`c_id`  varchar(128) NOT NULL COMMENT '编号' ,
`c_name`  varchar(255) NULL COMMENT '名称' ,
`c_display_name`  varchar(128) NULL COMMENT '显示名称' ,
`c_status`  tinyint(1) NULL COMMENT '状态' ,
`c_modify_user`  varchar(128) NULL COMMENT '修改用户' ,
`c_create_user`  varchar(128) NULL COMMENT '创建用户' ,
`c_create_time`  datetime NULL COMMENT '创建时间' ,
`c_modify_time`  datetime NULL COMMENT '修改时间' ,
`c_account`  varchar(255) NULL COMMENT '账号' ,
`c_password`  varchar(255) NULL COMMENT '密码' ,
`c_sex`  varchar(16) NULL COMMENT '性别' ,
`c_icon`  varchar(255) NULL COMMENT '头像' ,
`c_email`  varchar(255) NULL COMMENT '邮箱' ,
`c_phone`  varchar(16) NULL COMMENT '电话' ,
`c_is_custom`  tinyint(1) NULL COMMENT '是否自定义' ,
`c_memo`  varchar(255) NULL COMMENT '备注' ,
`c_business_id`  varchar(128) NULL COMMENT '企业编号' ,
PRIMARY KEY (`c_id`) ,
UNIQUE KEY `uk_account` (`c_account`),
CONSTRAINT `fk_user_bid` FOREIGN KEY (`c_business_id`) REFERENCES `t_business` (`c_id`) ON UPDATE CASCADE
)comment='用户表';
